export const SHARED_INIT = 'SHARED_INIT'
export const SHARED_ADD_POINTS = 'SHARED_ADD_POINTS'

export const INIT = 'INIT'

export const DATA_READY = 'DATA_READY'
export const TOGGLE = 'TOGGLE'
export const SET_DB = 'SET_DB'

export const POUCH_READY = 'POUCH_READY'
export const POUCH_SYNC_CHANGE = 'POUCH_SYNC_CHANGE'
export const POUCH_SYNC_ERROR = 'POUCH_SYNC_ERROR'

export const CHOOSE_WORD_STOP = 'CHOOSE_WORD_STOP'
export const CHOOSE_WORD_CHECK = 'CHOOSE_WORD_CHECK'
export const CHOOSE_WORD_STEP = 'CHOOSE_WORD_STEP'
export const CHOOSE_WORD_SET_INDEX = 'CHOOSE_WORD_SET_INDEX'
export const CHOOSE_WORD_INIT = 'CHOOSE_WORD_INIT'
export const CHOOSE_WORD_LISTEN = 'CHOOSE_WORD_LISTEN'
export const CHOOSE_WORD_INIT_READY = 'CHOOSE_WORD_INIT_READY'
export const CHOOSE_WORD_NEXT = 'CHOOSE_WORD_NEXT'
export const CHOOSE_WORD_READY = 'CHOOSE_WORD_READY'
export const CHOOSE_WORD_SHOW = 'CHOOSE_WORD_SHOW'
export const CHOOSE_WORD_SET_NEXT = 'CHOOSE_WORD_SET_NEXT'

export const CARRIER_STOP = 'CARRIER_STOP'
export const CARRIER_CHECK = 'CARRIER_CHECK'
export const CARRIER_STEP = 'CARRIER_STEP'
export const CARRIER_SET_INDEX = 'CARRIER_SET_INDEX'
export const CARRIER_INIT = 'CARRIER_INIT'
export const CARRIER_LISTEN = 'CARRIER_LISTEN'
export const CARRIER_INIT_READY = 'CARRIER_INIT_READY'
export const CARRIER_NEXT = 'CARRIER_NEXT'
export const CARRIER_READY = 'CARRIER_READY'
export const CARRIER_SHOW = 'CARRIER_SHOW'

export const SMALL_DELAY = 150
