export const SHARED_INIT = 'SHARED_INIT'
export const SHARED_SPEAK = 'SHARED_SPEAK'
export const SHARED_ADD_POINTS = 'SHARED_ADD_POINTS'

export const INIT = 'INIT'

export const NAVIGATION_TOGGLE = 'NAVIGATION_TOGGLE'
export const NAVIGATION_CHANGE = 'NAVIGATION_CHANGE'

export const DATA_READY = 'DATA_READY'
export const SET_DB = 'SET_DB'

export const POUCH_READY = 'POUCH_READY'
export const POUCH_USER_READY = 'POUCH_USER_READY'
export const POUCH_USER_CHANGE = 'POUCH_USER_CHANGE'
export const POUCH_SYNC_CHANGE = 'POUCH_SYNC_CHANGE'

// SETTINGS
export const SETTINGS_RANDOM = 'SETTINGS_RANDOM'
export const SETTINGS_TEXT_TO_SPEECH = 'SETTINGS_TEXT_TO_SPEECH'

// WRITE_SENTENCE
export const WRITE_SENTENCE = 'WRITE_SENTENCE'
export const WRITE_SENTENCE_STOP = 'WRITE_SENTENCE_STOP'
export const WRITE_SENTENCE_CHECK = 'WRITE_SENTENCE_CHECK'
export const WRITE_SENTENCE_SET_INDEX = 'WRITE_SENTENCE_SET_INDEX'
export const WRITE_SENTENCE_INIT = 'WRITE_SENTENCE_INIT'
export const WRITE_SENTENCE_LISTEN = 'WRITE_SENTENCE_LISTEN'
export const WRITE_SENTENCE_INIT_READY = 'WRITE_SENTENCE_INIT_READY'
export const WRITE_SENTENCE_NEXT = 'WRITE_SENTENCE_NEXT'
export const WRITE_SENTENCE_READY = 'WRITE_SENTENCE_READY'
export const WRITE_SENTENCE_SHOW = 'WRITE_SENTENCE_SHOW'
export const WRITE_SENTENCE_STEP = 'WRITE_SENTENCE_STEP'
export const WRITE_SENTENCE_SET_NEXT = 'WRITE_SENTENCE_SET_NEXT'
export const WRITE_SENTENCE_SET_INPUT = 'WRITE_SENTENCE_SET_INPUT'

// LEARNING_MEME
export const LEARNING_MEME = 'LEARNING_MEME'
export const LEARNING_MEME_STOP = 'LEARNING_MEME_STOP'
export const LEARNING_MEME_CHECK = 'LEARNING_MEME_CHECK'
export const LEARNING_MEME_SET_INDEX = 'LEARNING_MEME_SET_INDEX'
export const LEARNING_MEME_INIT = 'LEARNING_MEME_INIT'
export const LEARNING_MEME_LISTEN = 'LEARNING_MEME_LISTEN'
export const LEARNING_MEME_INIT_READY = 'LEARNING_MEME_INIT_READY'
export const LEARNING_MEME_NEXT = 'LEARNING_MEME_NEXT'
export const LEARNING_MEME_READY = 'LEARNING_MEME_READY'
export const LEARNING_MEME_SHOW = 'LEARNING_MEME_SHOW'
export const LEARNING_MEME_SET_NEXT = 'LEARNING_MEME_SET_NEXT'
export const LEARNING_MEME_SET_INPUT = 'LEARNING_MEME_SET_INPUT'

// CHOOSE_WORD
export const CHOOSE_WORD = 'CHOOSE_WORD'
export const CHOOSE_WORD_STOP = 'CHOOSE_WORD_STOP'
export const CHOOSE_WORD_CHECK = 'CHOOSE_WORD_CHECK'
export const CHOOSE_WORD_STEP = 'CHOOSE_WORD_STEP'
export const CHOOSE_WORD_SET_INDEX = 'CHOOSE_WORD_SET_INDEX'
export const CHOOSE_WORD_INIT = 'CHOOSE_WORD_INIT'
export const CHOOSE_WORD_LISTEN = 'CHOOSE_WORD_LISTEN'
export const CHOOSE_WORD_INIT_READY = 'CHOOSE_WORD_INIT_READY'
export const CHOOSE_WORD_NEXT = 'CHOOSE_WORD_NEXT'
export const CHOOSE_WORD_READY = 'CHOOSE_WORD_READY'
export const CHOOSE_WORD_SHOW = 'CHOOSE_WORD_SHOW'
export const CHOOSE_WORD_SET_NEXT = 'CHOOSE_WORD_SET_NEXT'

// CARRIER
export const CARRIER_STOP = 'CARRIER_STOP'
export const CARRIER_CHECK = 'CARRIER_CHECK'
export const CARRIER_STEP = 'CARRIER_STEP'
export const CARRIER_SET_INDEX = 'CARRIER_SET_INDEX'
export const CARRIER_INIT = 'CARRIER_INIT'
export const CARRIER_LISTEN = 'CARRIER_LISTEN'
export const CARRIER_INIT_READY = 'CARRIER_INIT_READY'
export const CARRIER_NEXT = 'CARRIER_NEXT'
export const CARRIER_READY = 'CARRIER_READY'
export const CARRIER_SHOW = 'CARRIER_SHOW'

// USER
export const USER_REGISTER = 'USER_REGISTER'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_INIT = 'USER_INIT'

// ROUTER
export const ROUTER_CHANGE = '@@router/LOCATION_CHANGE'

// SMALL
export const NEXT_TICK = 0
export const SHORT_DELAY = 150
export const DELAY = 500
export const LONG_DELAY = 1000
